### ISSUE TITLE
composer require laravel-admin-ext/grid-lightbox

### ISSUE THREAD

**Issue by wuchenge** [laravel-admin-extensions/grid-lightbox#1]
[InvalidArgumentException]
  Could not find package laravel-admin-ext/grid-lightbox at any version for
   your minimum-stability (stable). Check the package spelling or your mini
  mum-stability

google is not help this.

**Comment by z-song** [comment]
https://packagist.org/packages/laravel-admin-ext/grid-lightbox

检查一下你的composer镜像配置

**Comment by wuchenge** [comment]
> https://packagist.org/packages/laravel-admin-ext/grid-lightbox
> 
> 检查一下你的composer镜像配置

确实是。我用的国内镜像。谢谢
